[tool.poetry]
name = "proteens"
version = "0.1.0"
description = ""
authors = ["shen <shen.pro@kakaopaycorp.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

